version: '3.3'

services:
  app:
    build: .
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    ports:
      - '5000:5000'
    expose:
      - '5000'
    volumes:
      - './insurance_db:/app/insurance_db'
    networks:
      - insurance_network

networks:
  insurance_network:
